# Generated by Django 4.1.9 on 2023-07-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdata',
            name='image',
            field=models.ImageField(default='images/None/No-img.jpg', upload_to='images/'),
        ),
    ]
